name: browserconfig
description: Adds XML browser configuration support
long_description: >-
  Browser configuration files (also known as browserconfig) can be used to
  define pinned site customizations, such as tile backgrounds, badge updates,
  and tile notifications. Browser configuration files let you set these
  customizations using external XML files rather than metadata within the HTML
  markup of a webpage
repo: nuxt-community/modules#master/packages/browserconfig
npm: '@nuxtjs/browserconfig'
type: module
icon: ''
github: 'https://github.com/nuxt-community/modules/tree/master/packages/browserconfig'
website: 'https://github.com/nuxt-community/modules/tree/master/packages/browserconfig'
learn_more: >-
  https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/dev-guides/bg183312(v=vs.85)?redirectedfrom=MSDN
keywords: []
categories:
  - devtools
labels:
  - community
maintainers:
  - name: Pooya Parsa
    github: pi0
    twitter: _pi0_
    avatar: 'https://github.com/pi0.png'
