name: netlify-cache
description: >-
  Nuxt.js module that uses netlify cache to speed up redeploy for Nuxt.js
  version < 2.14
repo: DreaMinder/nuxt-netlify-cache
npm: nuxt-netlify-cache
icon: netlify.png
github: 'https://github.com/DreaMinder/nuxt-netlify-cache'
website: 'https://github.com/DreaMinder/nuxt-netlify-cache'
learn_more: 'https://www.netlify.com/'
released_at: '2020-06-24T11:49:26.197Z'
category: Deployment
type: 3rd-party
maintainers:
  - name: DreaMinder
    github: DreaMinder
    avatar: 'https://avatars0.githubusercontent.com/u/2715278?v=4'
